-- Storage bucket for invoice PDFs uploaded when emailing customers.
-- Private bucket: customer access goes through short-lived signed URLs
-- generated by the CRM at email-send time.
--
-- Object path layout:  <user_id>/<invoice_number>-<timestamp>.pdf
-- This lets the RLS policies check that authenticated users can only
-- write to / read from their own folder.

insert into storage.buckets (id, name, public)
values ('invoice-pdfs', 'invoice-pdfs', false)
on conflict (id) do nothing;

drop policy if exists invoice_pdfs_owner_insert on storage.objects;
create policy invoice_pdfs_owner_insert on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'invoice-pdfs'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists invoice_pdfs_owner_select on storage.objects;
create policy invoice_pdfs_owner_select on storage.objects
  for select to authenticated
  using (
    bucket_id = 'invoice-pdfs'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists invoice_pdfs_owner_delete on storage.objects;
create policy invoice_pdfs_owner_delete on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'invoice-pdfs'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
